import type { LucideIcon } from 'lucide-react';
import { Activity, CircleHelp, Contact, CreditCard, Gauge, Gift, Globe2, KeyRound, LayoutDashboard, Network, Radio, Settings, ShieldCheck, Sparkles, UserRound, Users } from 'lucide-react';

export type RouteMode = 'backed' | 'unavailable' | 'protected';
export type RouteShell = 'public' | 'account' | 'console';
export type SiteGroup = 'workspace' | 'developer' | 'commercial' | 'community' | 'activities' | 'operator';
export type SiteRoute = { path: string; key: string; mode: RouteMode; shell: RouteShell; icon: LucideIcon; group?: SiteGroup };

const publicRoute = (path: string, key: string, mode: RouteMode = 'unavailable'): SiteRoute => ({ path, key, mode, shell: 'public', icon: Globe2 });
const accountRoute = (path: string, key: string, group: SiteGroup, icon: LucideIcon = UserRound): SiteRoute => ({ path, key, mode: 'unavailable', shell: 'account', group, icon });

export const routeManifest: SiteRoute[] = [
  publicRoute('/', 'home', 'backed'), publicRoute('/about', 'about'), publicRoute('/models', 'models'), publicRoute('/model-plaza', 'modelPlaza'), publicRoute('/network-status', 'networkStatus'), publicRoute('/status', 'status'), publicRoute('/login', 'login', 'backed'), publicRoute('/register', 'register'), publicRoute('/forgot-password', 'forgotPassword'), publicRoute('/contact', 'contact'), publicRoute('/contact/qq', 'contactSupport'), publicRoute('/docs', 'docs'), publicRoute('/docs/batch-image', 'batchImage'), publicRoute('/claude-code', 'claudeCode'), publicRoute('/codex', 'codex'),
  accountRoute('/account', 'accountOverview', 'workspace', LayoutDashboard), accountRoute('/account/profile', 'profile', 'workspace'), accountRoute('/account/usage', 'usage', 'workspace', Gauge), accountRoute('/account/requests', 'requestHistory', 'workspace', Activity), accountRoute('/account/keys', 'apiKeys', 'workspace', KeyRound), accountRoute('/account/key-usage', 'keyUsage', 'workspace', KeyRound), accountRoute('/account/models', 'availableModels', 'developer', Sparkles), accountRoute('/account/channels', 'availableChannels', 'developer', Radio), accountRoute('/account/groups', 'groups', 'workspace', Users), accountRoute('/account/settings', 'accountSettings', 'workspace', Settings), accountRoute('/account/announcements', 'announcements', 'workspace', CircleHelp), accountRoute('/account/audit', 'auditEvents', 'developer', ShieldCheck), accountRoute('/account/errors', 'errorEvents', 'developer', CircleHelp),
  accountRoute('/account/subscriptions', 'subscriptions', 'commercial', CreditCard), accountRoute('/account/purchase', 'purchase', 'commercial', CreditCard), accountRoute('/account/recharge', 'recharge', 'commercial', CreditCard), accountRoute('/account/payment-result', 'paymentResult', 'commercial', CreditCard), accountRoute('/account/receipt', 'receipt', 'commercial', CreditCard), accountRoute('/account/payment-plans', 'paymentPlans', 'commercial', CreditCard), accountRoute('/account/coupons', 'coupons', 'commercial', Gift), accountRoute('/account/redeem', 'redeem', 'commercial', Gift), accountRoute('/account/orders', 'orders', 'commercial', CreditCard), accountRoute('/account/balance-history', 'balanceHistory', 'commercial', CreditCard),
  accountRoute('/account/proxies', 'proxies', 'developer', Network), accountRoute('/account/endpoint-distribution', 'endpointDistribution', 'developer', Network), accountRoute('/account/prompt-audit', 'promptAudit', 'developer', ShieldCheck), accountRoute('/account/risk-control', 'riskControl', 'developer', ShieldCheck), accountRoute('/account/channel-monitor', 'channelMonitor', 'developer', Radio), accountRoute('/account/channel-status', 'channelStatus', 'developer', Radio),
  accountRoute('/account/affiliate', 'affiliate', 'community', Users), accountRoute('/account/agent-team', 'agentTeam', 'community', Users), accountRoute('/account/agent-contact', 'agentContact', 'community', Contact), accountRoute('/account/withdrawals', 'withdrawals', 'community', CreditCard),
  accountRoute('/account/arena', 'arena', 'activities', Sparkles), accountRoute('/account/arena-winners', 'arenaWinners', 'activities', Sparkles), accountRoute('/account/quiz', 'quiz', 'activities', CircleHelp), accountRoute('/account/quiz-stats', 'quizStats', 'activities', CircleHelp), accountRoute('/account/blind-box', 'blindBox', 'activities', Gift), accountRoute('/account/blind-box/manage', 'blindBoxManagement', 'activities', Gift), accountRoute('/account/blind-box/probability', 'blindBoxProbability', 'activities', Gift), accountRoute('/account/achievements', 'achievements', 'activities', Sparkles), accountRoute('/account/badges', 'badges', 'activities', Sparkles), accountRoute('/account/check-in', 'checkIn', 'activities', Gift),
  accountRoute('/operator', 'operationsDashboard', 'operator', LayoutDashboard), accountRoute('/operator/users', 'operatorUsers', 'operator', Users), accountRoute('/operator/accounts', 'operatorAccounts', 'operator', Users), accountRoute('/operator/groups', 'operatorGroups', 'operator', Users), accountRoute('/operator/channels', 'operatorChannels', 'operator', Radio), accountRoute('/operator/orders', 'operatorOrders', 'operator', CreditCard), accountRoute('/operator/payment-dashboard', 'paymentDashboard', 'operator', CreditCard), accountRoute('/operator/payment-plans', 'operatorPaymentPlans', 'operator', CreditCard), accountRoute('/operator/affiliate-invites', 'affiliateInvites', 'operator', Users), accountRoute('/operator/affiliate-rebates', 'affiliateRebates', 'operator', Users), accountRoute('/operator/affiliate-transfers', 'affiliateTransfers', 'operator', Users), accountRoute('/operator/affiliate-records', 'affiliateRecords', 'operator', Users), accountRoute('/operator/agent-applications', 'agentApplications', 'operator', Users), accountRoute('/operator/agent-config', 'agentConfiguration', 'operator', Settings), accountRoute('/operator/agent-list', 'agentList', 'operator', Users), accountRoute('/operator/agent-withdrawals', 'agentWithdrawals', 'operator', CreditCard), accountRoute('/operator/audit-log', 'operatorAuditLog', 'operator', ShieldCheck), accountRoute('/operator/ops-dashboard', 'operationsDashboard', 'operator', LayoutDashboard), accountRoute('/operator/error-log', 'operatorErrorLog', 'operator', CircleHelp),
];

export const publicRoutes = routeManifest.filter((route) => route.shell === 'public');
export const accountRoutes = routeManifest.filter((route) => route.shell === 'account');
