import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, CheckCircle2, FileText, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Card, Button } from '@/components/ui';
import { UnavailableState } from '@/components/site/UnavailableState';
import { useLocale } from '@/i18n/context';
import type { SiteRoute } from '@/routes/manifest';

function PublicUnavailable({ body }: { body: string }) {
  const { t } = useLocale();
  return <Card className="mx-auto max-w-3xl py-12 text-center"><LockKeyhole className="mx-auto mb-4 text-surface-400" size={28} aria-hidden="true" /><h2 className="text-xl font-semibold text-surface-900">{t.site.actions.unavailable}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-surface-500">{body}</p><Button className="mt-6" disabled aria-disabled="true">{t.site.actions.unavailable}</Button></Card>;
}

function HomePage() {
  const { t } = useLocale();
  return <div className="space-y-10"><section className="border-b border-surface-200 py-8 sm:py-14"><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.hero.eyebrow}</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold leading-tight text-surface-900 sm:text-5xl">{t.site.routes.home.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-surface-600">{t.site.routes.home.description}</p><div className="mt-7 flex flex-wrap gap-3"><Link className="btn-primary" to="/login">{t.site.actions.openWorkspace}<ArrowRight size={16} /></Link><Link className="btn-secondary" to="/docs">{t.site.actions.documentation}<BookOpen size={16} /></Link></div></section><section className="grid gap-4 md:grid-cols-3">{t.site.public.docsTopics.map((topic) => <Card key={topic}><ShieldCheck size={20} className="mb-5 text-primary-700" aria-hidden="true" /><h2 className="font-semibold text-surface-900">{topic}</h2><p className="mt-2 text-sm leading-6 text-surface-500">{t.site.hero.operationalDescription}</p></Card>)}</section></div>;
}

function AboutPage() { const { t } = useLocale(); return <article className="max-w-3xl space-y-6"><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.hero.eyebrow}</p><h1 className="text-3xl font-semibold text-surface-900">{t.site.routes.about.title}</h1><p className="text-base leading-8 text-surface-600">{t.site.public.aboutBody}</p><Card><h2 className="font-semibold text-surface-900">{t.site.hero.operationalTitle}</h2><p className="mt-2 text-sm leading-6 text-surface-500">{t.site.hero.operationalDescription}</p></Card></article>; }

function ModelsPage() { const { t } = useLocale(); return <div className="space-y-6"><h1 className="text-3xl font-semibold text-surface-900">{t.site.routes.models.title}</h1><p className="max-w-2xl text-base leading-7 text-surface-600">{t.site.public.modelsBody}</p><Card><div className="grid gap-3 border-b border-surface-200 pb-4 text-xs font-medium uppercase text-surface-500 sm:grid-cols-2"><span>{t.site.public.modelName}</span><span>{t.site.public.modelStatus}</span></div><div className="flex items-center gap-3 py-8 text-sm text-surface-500"><FileText size={18} aria-hidden="true" />{t.site.public.unavailableBody}</div></Card></div>; }

function StatusPage({ route }: { route: SiteRoute }) { const { t } = useLocale(); const copy = t.site.routes[route.key]; return <div className="space-y-6"><h1 className="text-3xl font-semibold text-surface-900">{copy.title}</h1><p className="max-w-2xl text-base leading-7 text-surface-600">{copy.description}</p><div className="grid gap-4 sm:grid-cols-2"><Card><CheckCircle2 className="mb-4 text-success" size={22} aria-hidden="true" /><h2 className="font-semibold text-surface-900">{t.site.public.statusOperational}</h2></Card><Card><LockKeyhole className="mb-4 text-surface-400" size={22} aria-hidden="true" /><h2 className="font-semibold text-surface-900">{t.site.public.statusUnavailable}</h2></Card></div></div>; }

function ContactPage({ support = false }: { support?: boolean }) { const { t } = useLocale(); return <div className="max-w-2xl space-y-6"><h1 className="text-3xl font-semibold text-surface-900">{t.site.routes[support ? 'contactSupport' : 'contact'].title}</h1><p className="text-base leading-7 text-surface-600">{support ? t.site.public.contactSupportBody : t.site.public.contactBody}</p><PublicUnavailable body={t.site.public.unavailableBody} /></div>; }

function DocsPage() { const { t } = useLocale(); return <div className="space-y-8"><div><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.hero.eyebrow}</p><h1 className="mt-3 text-3xl font-semibold text-surface-900">{t.site.routes.docs.title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-surface-600">{t.site.public.docsBody}</p></div><div className="grid gap-4 md:grid-cols-3">{t.site.public.docsTopics.map((topic) => <Card key={topic}><BookOpen size={20} className="mb-4 text-primary-700" aria-hidden="true" /><h2 className="font-semibold text-surface-900">{topic}</h2><p className="mt-2 text-sm text-surface-500">{t.site.public.docsBody}</p></Card>)}</div><Card><div className="flex items-center gap-3 text-sm text-surface-600"><FileText size={18} aria-hidden="true" />{t.site.public.unavailableBody}</div></Card></div>; }

const accountPresentationKeys = new Set(['accountOverview', 'profile', 'usage', 'requestHistory', 'apiKeys', 'keyUsage', 'availableModels', 'availableChannels', 'groups', 'accountSettings', 'announcements', 'auditEvents', 'errorEvents']);
const inertAccountFamilyGroups = new Set(['commercial', 'community', 'activities']);
const operatorRouteKeys = new Set(['operationsDashboard', 'operatorUsers', 'operatorAccounts', 'operatorGroups', 'operatorChannels', 'operatorOrders', 'paymentDashboard', 'operatorPaymentPlans', 'affiliateInvites', 'affiliateRebates', 'affiliateTransfers', 'affiliateRecords', 'agentApplications', 'agentConfiguration', 'agentList', 'agentWithdrawals', 'operatorAuditLog', 'operatorErrorLog']);
function AccountPresentationPage({ route }: { route: SiteRoute }) { const { t } = useLocale(); const copy = t.site.routes[route.key]; return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.account.groups[route.group as 'workspace' | 'developer']}</p><h1 className="mt-2 text-3xl font-semibold text-surface-900">{copy.title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-surface-600">{copy.description}</p></div><Button disabled aria-disabled="true">{route.key === 'auditEvents' || route.key === 'requestHistory' ? t.site.account.exportAction : t.site.account.editAction}</Button></div><Card><p className="text-sm leading-6 text-surface-500">{t.site.account.overviewBody}</p><div className="mt-6 grid grid-cols-2 border-y border-surface-200 py-3 text-xs font-medium uppercase text-surface-500"><span>{t.site.account.tableField}</span><span>{t.site.account.tableState}</span></div><div className="py-10 text-center text-sm text-surface-500">{t.site.account.emptyState}</div></Card><PublicUnavailable body={t.site.account.unavailableBody} /></div>; }
function InertAccountFamilyPage({ route }: { route: SiteRoute }) { const { t } = useLocale(); const copy = t.site.routes[route.key]; return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.account.groups[route.group as 'commercial' | 'community' | 'activities']}</p><h1 className="mt-2 text-3xl font-semibold text-surface-900">{copy.title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-surface-600">{copy.description}</p></div><Button disabled aria-disabled="true">{t.site.account.familyAction}</Button></div><div className="grid gap-4 sm:grid-cols-2"><Card><h2 className="font-semibold text-surface-900">{t.site.account.familyTitle}</h2><p className="mt-2 text-sm leading-6 text-surface-500">{t.site.account.familyBody}</p></Card><Card><div className="grid grid-cols-2 border-b border-surface-200 pb-3 text-xs font-medium uppercase text-surface-500"><span>{t.site.account.tableField}</span><span>{t.site.account.tableState}</span></div><p className="py-8 text-center text-sm text-surface-500">{t.site.account.familyState}</p></Card></div><PublicUnavailable body={t.site.account.unavailableBody} /></div>; }
function OperatorPage({ route }: { route: SiteRoute }) { const { t } = useLocale(); const copy = t.site.routes[route.key]; return <div className="space-y-6"><div><p className="text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.account.groups.operator}</p><h1 className="mt-2 text-3xl font-semibold text-surface-900">{copy.title}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-surface-600">{copy.description}</p></div><Card><div className="flex flex-wrap gap-3"><input aria-label={t.site.account.operatorSearch} disabled placeholder={t.site.account.operatorSearch} className="min-w-0 flex-1 rounded-md border border-surface-200 px-3 py-2 text-sm" /><Button disabled aria-label={t.site.account.operatorFilter}>{t.site.account.operatorFilter}</Button><Button disabled aria-label={t.site.account.operatorCreate}>{t.site.account.operatorCreate}</Button><Button disabled aria-label={t.site.account.operatorExport}>{t.site.account.operatorExport}</Button></div><div className="mt-6 grid grid-cols-2 border-y border-surface-200 py-3 text-xs font-medium uppercase text-surface-500"><span>{t.site.account.tableField}</span><span>{t.site.account.tableState}</span></div><p className="py-12 text-center text-sm text-surface-500">{t.site.account.familyState}</p></Card><PublicUnavailable body={t.site.account.operatorBody} /></div>; }

export function ManifestPage({ route }: { route: SiteRoute }) {
  const { t } = useLocale();
  const copy = t.site.routes[route.key] || t.site.fallback;
  if (route.key === 'home') return <HomePage />;
  if (route.key === 'about') return <AboutPage />;
  if (route.key === 'models') return <ModelsPage />;
  if (route.key === 'status' || route.key === 'networkStatus') return <StatusPage route={route} />;
  if (route.key === 'contact') return <ContactPage />;
  if (route.key === 'contactSupport') return <ContactPage support />;
  if (route.key === 'docs') return <DocsPage />;
  if (accountPresentationKeys.has(route.key)) return <AccountPresentationPage route={route} />;
  if (operatorRouteKeys.has(route.key)) return <OperatorPage route={route} />;
  if (inertAccountFamilyGroups.has(route.group || '')) return <InertAccountFamilyPage route={route} />;
  if (route.key === 'batchImage' || route.key === 'claudeCode' || route.key === 'codex' || route.key === 'modelPlaza') return <PublicUnavailable body={route.key === 'batchImage' || route.key === 'claudeCode' || route.key === 'codex' ? t.site.public.guideBody : t.site.public.unavailableBody} />;
  if (route.mode === 'unavailable') return <UnavailableState title={copy.title} description={copy.description} action={copy.action} />;
  const Icon = route.icon;
  return <section className="grid gap-8 py-6 lg:grid-cols-[1.2fr_0.8fr] lg:py-14"><div><p className="mb-3 text-xs font-medium uppercase tracking-wide text-primary-700">{t.site.hero.eyebrow}</p><h1 className="max-w-2xl text-3xl font-semibold leading-tight text-surface-900 sm:text-4xl">{copy.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-surface-600">{copy.description}</p></div><Card className="flex min-h-52 flex-col justify-between"><Icon size={28} className="text-primary-700" aria-hidden="true" /><div><h2 className="font-semibold text-surface-900">{t.site.hero.operationalTitle}</h2><p className="mt-2 text-sm leading-6 text-surface-500">{t.site.hero.operationalDescription}</p></div></Card></section>;
}
